readsDir: /scratch2/kaliappa/cfdna/rb/frag_len_aug27/reads
read1Suffix: _R1_001.fastq.gz
read2Suffix: _R2_001.fastq.gz

nThreads: 16  

fastqc: /scratch2/kaliappa/tools/fastqc/FastQC/fastqc

bwa: /scratch2/kaliappa/tools/bwa/bwa-0.7.17/bwa
ref: /scratch2/kaliappa/tools/bwa/hg19/hg19.fa

minMapq: 30


picard: /scratch2/kaliappa/tools/picard/picard.jar
