readsDir: /scratch2/kaliappa/cfdna/rb/rb_altered_frag_len/reads
read1Suffix: _1.fastq.gz
read2Suffix: _2.fastq.gz

nThreads: 14

fastqc: /scratch2/kaliappa/tools/fastqc/FastQC/fastqc

bwa: /scratch2/kaliappa/tools/bwa/bwa-0.7.17/bwa
ref: /scratch2/kaliappa/tools/bwa/hg19/hg19.fa

minMapq: 30

minInsertLen: 50
maxInsertLen: 250
picard: /scratch2/kaliappa/tools/picard/picard.jar
normalzedInsertLen: /scratch2/kaliappa/cfdna/cfDNA_utils/scripts/insertLenDist.R
