fastqc: /scratch2/kaliappa/tools/fastqc/FastQC/fastqc
bwa: /scratch2/kaliappa/tools/bwa/bwa-0.7.17/bwa
ref: /scratch2/kaliappa/tools/bwa/hg19/hg19.fa
picard: /scratch2/kaliappa/tools/picard/picard.jar

minMapq: 30

samples:
  - CHLA_RR_023_OS_DX
