fastqc: /staging/as/kaliappa/tmp/fastqc/FastQC/fastqc

bwa: /staging/as/kaliappa/bwa/bwa-0.7.17/bwa
ref: /home/cmb-panasas2/kaliappa/data/hg19/bwa/hg19.fa

mapStats: $REPO_PATH/scripts/mapStats.py 

readCounter: 
  /staging/as/kaliappa/tmp/ichor/hmmcopy_utils/bin/readCounter
readCounterBinSize: 1000000
readCounterChrs: >-
  chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY

ichor:
  /staging/as/kaliappa/tmp/ichor/ichorCNA/scripts/runIchorCNA.R
ichorGcWig:
  /staging/as/kaliappa/tmp/ichor/ichorCNA/inst/extdata/gc_hg19_1000kb.wig
ichorMapWig:
  /staging/as/kaliappa/tmp/ichor/ichorCNA/inst/extdata/map_hg19_1000kb.wig
ichorCentromere:
  /staging/as/kaliappa/tmp/ichor/ichorCNA/inst/extdata/GRCh37.p13_centromere_UCSC-gapTable.txt
ichorPloidy:
  c(2,3)
ichorNormal:
  c(0.5,0.6,0.7,0.8,0.9)
ichorMaxCn:
  5
ichorScStates:
  c(1,3)
ichorTxnE:
  0.9999
ichorTxnStrength:
  10000

samples:
  - 2017_001_OD_A_CGATGTAT_L002
